homeassistant:
  customize:
    script.group_visibility:
      hidden: true
    automation.hide_and_unhide:
      hidden: true

input_boolean:
  hide_group:
    name: "Hide Group"
    initial: off

automation:
  - alias: "Hide and Unhide"
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: input_boolean.hide_group
    action:
      service: script.group_visibility
      data:
        entity_id: group. ##GROUP NAME HERE
        cond: input_boolean.hide_group
        visible_state: 'off'

script:
  group_visibility:
    sequence:
      - service: group.set_visibility
        data_template:
          entity_id: '{{ entity_id }}'
          visible: '{{ is_state(cond, visible_state) }}'

group:
  hide_group_group:
   view: false
   control: hidden
   entities:
   - input_boolean.hide_group
   - automation.hide_and_unhide
   - script.group_visibility
