input_boolean:
  hide_group_001:
    name: "Hide Group 001"
    initial: off

automation:
  - alias: "hideunhide_automation_001"
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: input_boolean.hide_group_001
    action:
      service: script.group_visibility
      data:
        entity_id: [[[YOUR GROUP ENTITY]]]
        cond: input_boolean.hide_group_001
        visible_state: 'off'
