###################################################################
##                                                             ####
##     https://home-assistant.io/components/joaoapps_join/     ####
##          add notify and joaoapps_join components            ####
##             Change "Contact #" to your desire               ####
###################################################################

homeassistant:
  customize:
    script.join_mega_script:
      icon: mdi:email
    input_text.msg_text:
      icon: mdi:comment-text-outline
    input_text.phone_number:
      icon: mdi:phone-classic
    input_text.join_url:
      icon: mdi:web
    input_text.join_cmd:
      icon: mdi:console
    input_select.contact_list:
      icon: mdi:account-group
    input_select.join_services:
      icon: mdi:sitemap
  customize_glob:
    "script.join_script_*":
      hidden: true

group:
  join_joaoapps:
    name: "Join"
    control: hidden
    view: no
    entities:
      - input_select.contact_list
      - input_text.phone_number
      - input_text.msg_text
      - input_text.join_url
      - input_text.join_cmd
      - input_select.join_services
      - script.join_mega_script
notify:
  - platform: joaoapps_join
    name: Join
    api_key: 
    device_id: 
    device_names: 

joaoapps_join:
  - name: sthope
    device_id: 
    api_key: 

input_select:
  join_services:
    name: Join Services
    options:
     - Send SMS
     - Send File
     - Send URL
     - Send Tasker
     - Ring
     - Set Wallpaper
    initial: Send SMS

  contact_list:
    name: Contacts
    options:
     - Contact 1
     - Contact 2
     - Contact 3
     - Contact 4
     - Contact 5
     - "."        ## with this option we can set the phone number in the Number input_text
    initial: "."

input_text:
  msg_text:
    name: "SMS:"
    initial: ""

  phone_number:
    name: "Number:"
    max: 13
    initial: ""

  join_url:
    name: "URL:"
    initial: URL address

  join_cmd:
    name: "Command:"
    initial: Tasker Command

script:
  join_script_ring:
    alias: "Script Join Ring"
    sequence:
      - service: joaoapps_join.sthope_ring
      
  join_script_send_file:
    alias: "Script Join Send File"
    sequence:
      - service: joaoapps_join.sthope_send_file
        data_template:
          url: '{{ states("input_text.join_url") }}'
      - delay: 00:00:01
      - service: input_text.set_value
        data:
          entity_id: input_text.join_url
          value: URL address
          
  join_script_send_sms:
    alias: "Script Join Send SMS"
    sequence:
      - service: joaoapps_join.sthope_send_sms
        data_template:
          message: '{{ states("input_text.msg_text") }}'
          number: >
            {% if is_state("input_select.contact_list", "Contact 1") %} 
            {% elif is_state("input_select.contact_list", "Contact 2") %} 
            {% elif is_state("input_select.contact_list", "Contact 3") %} 
            {% elif is_state("input_select.contact_list", "Contact 4") %} 
            {% elif is_state("input_select.contact_list", "Contact 5") %} 
            {% elif is_state("input_select.contact_list", ".") %} {{ states("input_text.phone_number") }}
            {% endif %}
      - delay: 00:00:05
      - service: input_text.set_value
        data:
          entity_id: input_text.msg_text
          value: ""
      - service: input_text.set_value
        data:
          entity_id: input_text.phone_number
          value: ""
          
  join_script_send_tasker:
    alias: "Script Join Send Tasker"
    sequence:
      - service: joaoapps_join.sthope_send_tasker
        data_template:
          command: '{{ states("input_text.join_cmd") }}'
      - delay: 00:00:01
      - service: input_text.set_value
        data:
          entity_id: input_text.join_cmd
          value: Tasker Command
          
  join_script_send_url:
    alias: "Script Join Send URL"
    sequence:
      - service: joaoapps_join.sthope_send_url
        data_template:
          url: '{{ states("input_text.join_url") }}'
      - delay: 00:00:01
      - service: input_text.set_value
        data:
          entity_id: input_text.join_url
          value: URL address
          
  join_script_set_wallpaper:
    alias: "Script Join Send URL"
    sequence:
      - service: joaoapps_join.sthope_set_wallpaper
        data_template:
          url: '{{ states("input_text.join_url") }}'
      - delay: 00:00:01
      - service: input_text.set_value
        data:
          entity_id: input_text.join_url
          value: URL address
          
  join_mega_script:
    alias: "Send"
    sequence:
      - service: homeassistant.turn_on 
        data_template:
          entity_id: >
           {% if is_state("input_select.join_services", "Ring") %} script.join_script_ring
           {% elif is_state("input_select.join_services", "Send File") %} script.join_script_send_file
           {% elif is_state("input_select.join_services", "Send SMS") %} script.join_script_send_sms
           {% elif is_state("input_select.join_services", "Send Tasker") %} script.join_script_send_tasker
           {% elif is_state("input_select.join_services", "Send URL") %} script.join_script_send_url
           {% elif is_state("input_select.join_services", "Set Wallpaper") %} script.join_script_set_wallpaper
           {% endif %}
